name: Deploy and Create File on EC2

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: SSH into EC2 and Create File
        run: |
          cat test-atul-newrelic.pem > private_key 
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-3-139-90-56.us-east-2.compute.amazonaws.com 'echo "Hello, EC2!" > test_file.txt'
