name: Deploy and Create File on EC2

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: SSH into EC2 and Create File
        run: |
          # cat test-atul-newrelic.pem > private_key 
          # chmod 600 private_key
          # ssh Atul@20.246.88.250   
          echo "this is data for sonarqube"
          # ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-3-139-90-56.us-east-2.compute.amazonaws.com 'echo "Hello, EC2!" > test_file.txt'

      # - name: Integration with New Relic
      #   run: |
      #     curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo  NEW_RELIC_API_KEY=NRAK-3TRAYKZTSUXDLT819HI11C8GISY NEW_RELIC_ACCOUNT_ID=3771867 /usr/local/bin/newrelic install
          
